"""initial mgration

Revision ID: 857363e8d3a6
Revises: 
Create Date: 2020-06-19 14:39:35.951172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "857363e8d3a6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("commune_name", sa.String(length=64), nullable=True),
        sa.Column("district_name", sa.String(length=64), nullable=True),
        sa.Column("province_name", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "indexes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("bad", sa.Integer(), nullable=True),
        sa.Column("sufficient", sa.Integer(), nullable=True),
        sa.Column("moderate", sa.Integer(), nullable=True),
        sa.Column("good", sa.Integer(), nullable=True),
        sa.Column("very_good", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("gegrLat", sa.Float(), nullable=True),
        sa.Column("gegrLon", sa.Float(), nullable=True),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sensors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=True),
        sa.Column("index_id", sa.Integer(), nullable=True),
        sa.Column("station_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["index_id"], ["indexes.id"],),
        sa.ForeignKeyConstraint(["station_id"], ["stations.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("sensor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["sensor_id"], ["sensors.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data")
    op.drop_table("sensors")
    op.drop_table("stations")
    op.drop_table("indexes")
    op.drop_table("cities")
    # ### end Alembic commands ###
