"""unique value to data table

Revision ID: fefea40b9ff8
Revises: 857363e8d3a6
Create Date: 2020-07-06 10:17:25.788900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fefea40b9ff8"
down_revision = "857363e8d3a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "data", ["date"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "data", type_="unique")
    # ### end Alembic commands ###
